package pl.fabrykaterapii.reservations.api;
import jakarta.validation.constraints.*; import pl.fabrykaterapii.reservations.domain.*; import java.math.BigDecimal; import java.time.*; import java.util.*;
public final class ApiDtos {
 private ApiDtos(){}
 public record ClientRequest(@NotBlank String firstName,@NotBlank String lastName,@NotBlank String phone,@Email String email,LocalDate birthDate,@AssertTrue(message="zgoda na przetwarzanie danych jest wymagana") boolean personalDataConsent,boolean communicationConsent,String administrativeNote){}
 public record ClientResponse(String id,String firstName,String lastName,String phone,String email,LocalDate birthDate,boolean personalDataConsent,boolean communicationConsent,String administrativeNote){ static ClientResponse of(Client c){return new ClientResponse(c.getId(),c.getFirstName(),c.getLastName(),c.getPhone(),c.getEmail(),c.getBirthDate(),c.isPersonalDataConsent(),c.isCommunicationConsent(),c.getAdministrativeNote());}}
 public record SpecialistRequest(@NotBlank String firstName,@NotBlank String lastName,@NotBlank String specialization,String color){} public record SpecialistResponse(String id,String firstName,String lastName,String specialization,String color,boolean active){static SpecialistResponse of(Specialist s){return new SpecialistResponse(s.getId(),s.getFirstName(),s.getLastName(),s.getSpecialization(),s.getColor(),s.isActive());}}
 public record RoomRequest(@NotBlank String name,String equipment){} public record RoomResponse(String id,String name,String equipment,boolean active){static RoomResponse of(Room r){return new RoomResponse(r.getId(),r.getName(),r.getEquipment(),r.isActive());}}
 public record TherapyServiceRequest(@NotBlank String name,@Positive Integer suggestedDurationMinutes,@PositiveOrZero BigDecimal defaultPrice,String requiredEquipment){} public record TherapyServiceResponse(String id,String name,Integer suggestedDurationMinutes,BigDecimal defaultPrice,String requiredEquipment){static TherapyServiceResponse of(TherapyService s){return new TherapyServiceResponse(s.getId(),s.getName(),s.getSuggestedDurationMinutes(),s.getDefaultPrice(),s.getRequiredEquipment());}}
 public record AppointmentRequest(@NotBlank String clientId,@NotBlank String specialistId,@NotBlank String roomId,String serviceId,@NotNull LocalDateTime startsAt,@NotNull LocalDateTime endsAt,@PositiveOrZero BigDecimal price,boolean paid,String note){}
 public record AppointmentResponse(String id,String clientId,String specialistId,String roomId,String serviceId,LocalDateTime startsAt,LocalDateTime endsAt,AppointmentStatus status,BigDecimal price,boolean paid,String note){static AppointmentResponse of(Appointment a){return new AppointmentResponse(a.getId(),a.getClient().getId(),a.getSpecialist().getId(),a.getRoom().getId(),a.getService()==null?null:a.getService().getId(),a.getStartsAt(),a.getEndsAt(),a.getStatus(),a.getPrice(),a.isPaid(),a.getNote());}}
 public record BlockRequest(String specialistId,String roomId,@NotNull LocalDateTime startsAt,@NotNull LocalDateTime endsAt,@NotNull BlockType type,String reason){} public record BlockResponse(String id,String specialistId,String roomId,LocalDateTime startsAt,LocalDateTime endsAt,BlockType type,String reason){static BlockResponse of(AvailabilityBlock b){return new BlockResponse(b.getId(),b.getSpecialist()==null?null:b.getSpecialist().getId(),b.getRoom()==null?null:b.getRoom().getId(),b.getStartsAt(),b.getEndsAt(),b.getType(),b.getReason());}}
 public record StatusRequest(@NotNull AppointmentStatus status){}
}
