package pl.fabrykaterapii.reservations.api;
import jakarta.validation.constraints.*; import pl.fabrykaterapii.reservations.domain.*; import java.math.BigDecimal; import java.time.*; import java.util.*;
public final class ApiDtos {
 private ApiDtos(){}
 public record ClientRequest(@NotBlank String firstName,@NotBlank String lastName,@NotBlank String phone,@Email String email,LocalDate birthDate,@AssertTrue(message="zgoda na przetwarzanie danych jest wymagana") boolean personalDataConsent,boolean communicationConsent,String administrativeNote){}
 public record ClientResponse(String id,String firstName,String lastName,String phone,String email,LocalDate birthDate,boolean personalDataConsent,boolean communicationConsent,String administrativeNote){ static ClientResponse of(Client c){return new ClientResponse(c.getId(),c.getFirstName(),c.getLastName(),c.getPhone(),c.getEmail(),c.getBirthDate(),c.isPersonalDataConsent(),c.isCommunicationConsent(),c.getAdministrativeNote());}}
 public record SpecialistRequest(@NotBlank String firstName,@NotBlank String lastName,@NotBlank String specialization,String color,String primaryRoomId,List<String> alternativeRoomIds){} public record SpecialistResponse(String id,String firstName,String lastName,String specialization,String color,boolean active,String primaryRoomId,List<String> alternativeRoomIds){static SpecialistResponse of(Specialist s){return new SpecialistResponse(s.getId(),s.getFirstName(),s.getLastName(),s.getSpecialization(),s.getColor(),s.isActive(),s.getPrimaryRoom()==null?null:s.getPrimaryRoom().getId(),s.getAlternativeRooms().stream().map(Room::getId).toList());}}
 public record RoomRequest(@NotBlank String name,@NotBlank String shortName,String equipment){} public record RoomResponse(String id,String name,String shortName,String equipment,boolean active){static RoomResponse of(Room r){return new RoomResponse(r.getId(),r.getName(),r.getShortName(),r.getEquipment(),r.isActive());}}
 public record TherapyServiceRequest(@NotBlank String name,@Positive Integer suggestedDurationMinutes,@NotNull @PositiveOrZero @Digits(integer=10,fraction=2) BigDecimal defaultPrice,String requiredEquipment,@Size(max=500) String description){} public record TherapyServiceResponse(String id,String name,Integer suggestedDurationMinutes,BigDecimal defaultPrice,String requiredEquipment,String description,boolean deleted){static TherapyServiceResponse of(TherapyService s){return new TherapyServiceResponse(s.getId(),s.getName(),s.getSuggestedDurationMinutes(),s.getDefaultPrice(),s.getRequiredEquipment(),s.getDescription(),s.isDeleted());}}
 public record AppointmentRequest(@NotBlank String clientId,@NotBlank String specialistId,@NotBlank String roomId,String serviceId,@NotNull LocalDateTime startsAt,@NotNull LocalDateTime endsAt,@PositiveOrZero BigDecimal price,boolean paid,String note,String recurrence,LocalDate recurrenceEndDate,Integer recurrenceInterval,String recurrenceUnit,Set<DayOfWeek> recurrenceDays,boolean updateSeries,Boolean confirmed){}
 public record AppointmentResponse(String id,String clientId,String specialistId,String roomId,String serviceId,LocalDateTime startsAt,LocalDateTime endsAt,AppointmentStatus status,BigDecimal price,boolean paid,String note,String recurrenceGroupId,String recurrenceType){static AppointmentResponse of(Appointment a){return new AppointmentResponse(a.getId(),a.getClient().getId(),a.getSpecialist().getId(),a.getRoom().getId(),a.getService()==null?null:a.getService().getId(),a.getStartsAt(),a.getEndsAt(),a.getStatus(),a.getPrice(),a.isPaid(),a.getNote(),a.getRecurrenceGroupId(),a.getRecurrenceType());}}
 public record BlockRequest(String specialistId,String roomId,@NotNull LocalDateTime startsAt,@NotNull LocalDateTime endsAt,@NotNull BlockType type,String reason){} public record BlockResponse(String id,String specialistId,String roomId,LocalDateTime startsAt,LocalDateTime endsAt,BlockType type,String reason){static BlockResponse of(AvailabilityBlock b){return new BlockResponse(b.getId(),b.getSpecialist()==null?null:b.getSpecialist().getId(),b.getRoom()==null?null:b.getRoom().getId(),b.getStartsAt(),b.getEndsAt(),b.getType(),b.getReason());}}
 public record StatusRequest(@NotNull AppointmentStatus status){}
 public record WorkScheduleRequest(@NotNull LocalDate startDate,LocalDate endDate,@NotNull LocalTime startTime,@NotNull LocalTime endTime,@NotNull WorkScheduleRecurrence recurrence,Set<DayOfWeek> daysOfWeek){}
 public record WorkScheduleResponse(String id,String specialistId,LocalDate startDate,LocalDate endDate,LocalTime startTime,LocalTime endTime,WorkScheduleRecurrence recurrence,Set<DayOfWeek> daysOfWeek){static WorkScheduleResponse of(WorkSchedule s){return new WorkScheduleResponse(s.getId(),s.getSpecialist().getId(),s.getStartDate(),s.getEndDate(),s.getStartTime(),s.getEndTime(),s.getRecurrence(),s.getDaysOfWeek());}}
}
