package pl.fabrykaterapii.reservations.api;
import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import pl.fabrykaterapii.reservations.api.ApiDtos.*; import pl.fabrykaterapii.reservations.domain.*; import pl.fabrykaterapii.reservations.repository.*; import java.util.*;
@RestController @RequestMapping("/api")
public class ManagementController {
 private final ClientRepository clients; private final SpecialistRepository specialists; private final RoomRepository rooms; private final TherapyServiceRepository services; private final AvailabilityBlockRepository blocks; private final WorkScheduleRepository schedules; private final AppointmentRepository appointments;
 public ManagementController(ClientRepository clients,SpecialistRepository specialists,RoomRepository rooms,TherapyServiceRepository services,AvailabilityBlockRepository blocks,WorkScheduleRepository schedules,AppointmentRepository appointments){this.clients=clients;this.specialists=specialists;this.rooms=rooms;this.services=services;this.blocks=blocks;this.schedules=schedules;this.appointments=appointments;}
 private List<Room> roomPreferences(List<String> ids){if(ids==null)return List.of();var unique=new LinkedHashSet<>(ids);return unique.stream().map(id->rooms.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono gabinetu"))).toList();} private Room primaryRoom(String id){return id==null||id.isBlank()?null:rooms.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono gabinetu głównego"));}
 private void ensureScheduleDoesNotInvalidateVisits(WorkSchedule changed){var proposed=new ArrayList<>(schedules.findBySpecialistId(changed.getSpecialist().getId()));proposed.removeIf(s->s.getId().equals(changed.getId()));proposed.add(changed);var terminal=Set.of(AppointmentStatus.CANCELLED_BY_CLIENT,AppointmentStatus.CANCELLED_BY_CLINIC,AppointmentStatus.NO_SHOW);for(Appointment appointment:appointments.findActiveBySpecialistId(changed.getSpecialist().getId(),terminal))if(proposed.stream().noneMatch(s->s.covers(appointment.getStartsAt(),appointment.getEndsAt())))throw new IllegalArgumentException("Zmiana grafiku koliduje z wizytą " + appointment.getStartsAt() + ". Najpierw odwołaj, usuń lub przełóż tę wizytę.");}
 @GetMapping("/clients") @PreAuthorize("hasAnyRole('OWNER','MANAGER','RECEPTION','SPECIALIST')") List<ClientResponse> clients(){return clients.findAll().stream().map(ClientResponse::of).toList();}
 @PostMapping("/clients") @PreAuthorize("hasAnyRole('OWNER','MANAGER','RECEPTION')") ResponseEntity<ClientResponse> client(@jakarta.validation.Valid @RequestBody ClientRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ClientResponse.of(clients.save(new Client(r.firstName(),r.lastName(),r.phone(),r.email(),r.birthDate(),r.personalDataConsent(),r.communicationConsent(),r.administrativeNote()))));}
 @PatchMapping("/clients/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER','RECEPTION')") ClientResponse updateClient(@PathVariable String id,@jakarta.validation.Valid @RequestBody ClientRequest r){Client c=clients.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono klienta"));c.update(r.firstName(),r.lastName(),r.phone(),r.email(),r.birthDate(),r.personalDataConsent(),r.communicationConsent(),r.administrativeNote());return ClientResponse.of(c);}
 @DeleteMapping("/clients/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<Void> deleteClient(@PathVariable String id){if(appointments.existsByClientId(id))throw new IllegalArgumentException("Nie można usunąć klienta z historią wizyt");clients.deleteById(id);return ResponseEntity.noContent().build();}
 @GetMapping("/specialists") List<SpecialistResponse> specialists(){return specialists.findAll().stream().map(SpecialistResponse::of).toList();}
 @PostMapping("/specialists") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<SpecialistResponse> specialist(@jakarta.validation.Valid @RequestBody SpecialistRequest r){if(r.color()!=null&&specialists.existsByColor(r.color()))throw new IllegalArgumentException("Ten kolor jest już przypisany do innego specjalisty");Specialist s=new Specialist(r.firstName(),r.lastName(),r.specialization(),r.color());s.setRoomPreferences(primaryRoom(r.primaryRoomId()),roomPreferences(r.alternativeRoomIds()));s=specialists.save(s);schedules.save(new WorkSchedule(s,java.time.LocalDate.of(2020,1,1),null,java.time.LocalTime.of(8,0),java.time.LocalTime.of(18,0),WorkScheduleRecurrence.WEEKLY,Set.of(java.time.DayOfWeek.MONDAY,java.time.DayOfWeek.TUESDAY,java.time.DayOfWeek.WEDNESDAY,java.time.DayOfWeek.THURSDAY,java.time.DayOfWeek.FRIDAY)));return ResponseEntity.status(HttpStatus.CREATED).body(SpecialistResponse.of(s));}
 @PatchMapping("/specialists/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") SpecialistResponse updateSpecialist(@PathVariable String id,@jakarta.validation.Valid @RequestBody SpecialistRequest r){Specialist specialist=specialists.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono specjalisty"));if(r.color()!=null&&specialists.existsByColorAndIdNot(r.color(),id))throw new IllegalArgumentException("Ten kolor jest już przypisany do innego specjalisty");specialist.update(r.firstName(),r.lastName(),r.specialization(),r.color());specialist.setRoomPreferences(primaryRoom(r.primaryRoomId()),roomPreferences(r.alternativeRoomIds()));return SpecialistResponse.of(specialists.save(specialist));}
 @DeleteMapping("/specialists/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<Void> deleteSpecialist(@PathVariable String id){if(appointments.existsBySpecialistId(id))throw new IllegalArgumentException("Nie można usunąć specjalisty z wizytami");schedules.findBySpecialistId(id).forEach(schedules::delete);specialists.deleteById(id);return ResponseEntity.noContent().build();}
 @GetMapping("/specialists/{id}/work-schedules") List<WorkScheduleResponse> workSchedules(@PathVariable String id){return schedules.findBySpecialistId(id).stream().map(WorkScheduleResponse::of).toList();}
 @GetMapping("/work-schedules") List<WorkScheduleResponse> allWorkSchedules(){if(schedules.count()==0){var weekdays=Set.of(java.time.DayOfWeek.MONDAY,java.time.DayOfWeek.TUESDAY,java.time.DayOfWeek.WEDNESDAY,java.time.DayOfWeek.THURSDAY);for(Specialist specialist:specialists.findAll())schedules.save(new WorkSchedule(specialist,java.time.LocalDate.of(2020,1,1),null,java.time.LocalTime.of(9,0),java.time.LocalTime.of(15,0),WorkScheduleRecurrence.WEEKLY,weekdays));}return schedules.findAll().stream().map(WorkScheduleResponse::of).toList();}
 @PostMapping("/specialists/{id}/work-schedules") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<WorkScheduleResponse> workSchedule(@PathVariable String id,@jakarta.validation.Valid @RequestBody WorkScheduleRequest r){if(!r.endTime().isAfter(r.startTime())||(r.endDate()!=null&&r.endDate().isBefore(r.startDate())))throw new IllegalArgumentException("Nieprawidłowy zakres grafiku");Specialist s=specialists.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono specjalisty"));var days=r.daysOfWeek()==null?Set.<java.time.DayOfWeek>of():r.daysOfWeek();if(r.recurrence()!=WorkScheduleRecurrence.ONCE&&days.isEmpty())throw new IllegalArgumentException("Wybierz co najmniej jeden dzień tygodnia");return ResponseEntity.status(HttpStatus.CREATED).body(WorkScheduleResponse.of(schedules.save(new WorkSchedule(s,r.startDate(),r.endDate(),r.startTime(),r.endTime(),r.recurrence(),days))));}
 @PatchMapping("/work-schedules/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") WorkScheduleResponse updateSchedule(@PathVariable String id,@jakarta.validation.Valid @RequestBody WorkScheduleRequest r){if(!r.endTime().isAfter(r.startTime())||(r.endDate()!=null&&r.endDate().isBefore(r.startDate())))throw new IllegalArgumentException("Nieprawidłowy zakres grafiku");var days=r.daysOfWeek()==null?Set.<java.time.DayOfWeek>of():r.daysOfWeek();if(r.recurrence()!=WorkScheduleRecurrence.ONCE&&days.isEmpty())throw new IllegalArgumentException("Wybierz co najmniej jeden dzień tygodnia");WorkSchedule schedule=schedules.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono grafiku"));schedule.update(r.startDate(),r.endDate(),r.startTime(),r.endTime(),r.recurrence(),days);ensureScheduleDoesNotInvalidateVisits(schedule);return WorkScheduleResponse.of(schedules.save(schedule));}
 @DeleteMapping("/work-schedules/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<Void> deleteSchedule(@PathVariable String id){WorkSchedule schedule=schedules.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono grafiku"));var proposed=schedules.findBySpecialistId(schedule.getSpecialist().getId()).stream().filter(s->!s.getId().equals(id)).toList();var terminal=Set.of(AppointmentStatus.CANCELLED_BY_CLIENT,AppointmentStatus.CANCELLED_BY_CLINIC,AppointmentStatus.NO_SHOW);for(Appointment appointment:appointments.findActiveBySpecialistId(schedule.getSpecialist().getId(),terminal))if(proposed.stream().noneMatch(s->s.covers(appointment.getStartsAt(),appointment.getEndsAt())))throw new IllegalArgumentException("Nie można usunąć tego zakresu: istnieje wizyta poza pozostałymi godzinami pracy. Najpierw przełóż lub odwołaj wizytę.");schedules.delete(schedule);return ResponseEntity.noContent().build();}
 @GetMapping("/rooms") List<RoomResponse> rooms(){return rooms.findAll().stream().map(RoomResponse::of).toList();}
 @PostMapping("/rooms") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<RoomResponse> room(@jakarta.validation.Valid @RequestBody RoomRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(RoomResponse.of(rooms.save(new Room(r.name(),r.shortName(),r.equipment()))));}
 @PatchMapping("/rooms/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") RoomResponse updateRoom(@PathVariable String id,@jakarta.validation.Valid @RequestBody RoomRequest r){Room room=rooms.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono gabinetu"));room.update(r.name(),r.shortName(),r.equipment());return RoomResponse.of(rooms.save(room));}
 @DeleteMapping("/rooms/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<Void> deleteRoom(@PathVariable String id){if(appointments.existsByRoomId(id))throw new IllegalArgumentException("Nie można usunąć gabinetu z wizytami");rooms.deleteById(id);return ResponseEntity.noContent().build();}
 @GetMapping("/services") List<TherapyServiceResponse> services(){return services.findAll().stream().map(TherapyServiceResponse::of).toList();}
 @PostMapping("/services") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<TherapyServiceResponse> service(@jakarta.validation.Valid @RequestBody TherapyServiceRequest r){validateServiceName(r.name(),null);var service=new TherapyService(r.name().trim(),r.suggestedDurationMinutes(),r.defaultPrice(),r.requiredEquipment());service.update(r.name(),r.suggestedDurationMinutes(),r.defaultPrice(),r.requiredEquipment(),r.description());return ResponseEntity.status(HttpStatus.CREATED).body(TherapyServiceResponse.of(services.save(service)));}
 private void validateServiceName(String name,String id){if(services.findAll().stream().anyMatch(s->!s.getId().equals(id)&&s.getName().equalsIgnoreCase(name.trim())))throw new IllegalArgumentException("Usługa o tej nazwie już istnieje. Wybierz inną nazwę.");}
 @PatchMapping("/services/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") TherapyServiceResponse updateService(@PathVariable String id,@jakarta.validation.Valid @RequestBody TherapyServiceRequest r){var service=services.findById(id).filter(s->!s.isDeleted()).orElseThrow(()->new NoSuchElementException("Nie znaleziono usługi"));validateServiceName(r.name(),id);service.update(r.name(),r.suggestedDurationMinutes(),r.defaultPrice(),r.requiredEquipment(),r.description());return TherapyServiceResponse.of(services.save(service));}
 @DeleteMapping("/services/{id}") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<Void> deleteService(@PathVariable String id){var service=services.findById(id).orElseThrow(()->new NoSuchElementException("Nie znaleziono usługi"));service.delete();services.save(service);return ResponseEntity.noContent().build();}
 @PostMapping("/blocks") @PreAuthorize("hasAnyRole('OWNER','MANAGER','RECEPTION','SPECIALIST')") ResponseEntity<BlockResponse> block(@jakarta.validation.Valid @RequestBody BlockRequest r){if((r.specialistId()==null)==(r.roomId()==null))throw new IllegalArgumentException("Blokada musi dotyczyć dokładnie jednego zasobu");if(!r.endsAt().isAfter(r.startsAt()))throw new IllegalArgumentException("Nieprawidłowy zakres blokady"); Specialist s=r.specialistId()==null?null:specialists.findById(r.specialistId()).orElseThrow(()->new NoSuchElementException("Nie znaleziono specjalisty"));Room room=r.roomId()==null?null:rooms.findById(r.roomId()).orElseThrow(()->new NoSuchElementException("Nie znaleziono gabinetu"));return ResponseEntity.status(HttpStatus.CREATED).body(BlockResponse.of(blocks.save(new AvailabilityBlock(s,room,r.startsAt(),r.endsAt(),r.type(),r.reason()))));}
}
