package pl.fabrykaterapii.reservations.api;
import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import pl.fabrykaterapii.reservations.api.ApiDtos.*; import pl.fabrykaterapii.reservations.domain.*; import pl.fabrykaterapii.reservations.repository.*; import java.util.*;
@RestController @RequestMapping("/api")
public class ManagementController {
 private final ClientRepository clients; private final SpecialistRepository specialists; private final RoomRepository rooms; private final TherapyServiceRepository services; private final AvailabilityBlockRepository blocks;
 public ManagementController(ClientRepository clients,SpecialistRepository specialists,RoomRepository rooms,TherapyServiceRepository services,AvailabilityBlockRepository blocks){this.clients=clients;this.specialists=specialists;this.rooms=rooms;this.services=services;this.blocks=blocks;}
 @GetMapping("/clients") @PreAuthorize("hasAnyRole('OWNER','MANAGER','RECEPTION','SPECIALIST')") List<ClientResponse> clients(){return clients.findAll().stream().map(ClientResponse::of).toList();}
 @PostMapping("/clients") @PreAuthorize("hasAnyRole('OWNER','MANAGER','RECEPTION')") ResponseEntity<ClientResponse> client(@jakarta.validation.Valid @RequestBody ClientRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ClientResponse.of(clients.save(new Client(r.firstName(),r.lastName(),r.phone(),r.email(),r.birthDate(),r.personalDataConsent(),r.communicationConsent(),r.administrativeNote()))));}
 @GetMapping("/specialists") List<SpecialistResponse> specialists(){return specialists.findAll().stream().map(SpecialistResponse::of).toList();}
 @PostMapping("/specialists") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<SpecialistResponse> specialist(@jakarta.validation.Valid @RequestBody SpecialistRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(SpecialistResponse.of(specialists.save(new Specialist(r.firstName(),r.lastName(),r.specialization(),r.color()))));}
 @GetMapping("/rooms") List<RoomResponse> rooms(){return rooms.findAll().stream().map(RoomResponse::of).toList();}
 @PostMapping("/rooms") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<RoomResponse> room(@jakarta.validation.Valid @RequestBody RoomRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(RoomResponse.of(rooms.save(new Room(r.name(),r.equipment()))));}
 @GetMapping("/services") List<TherapyServiceResponse> services(){return services.findAll().stream().map(TherapyServiceResponse::of).toList();}
 @PostMapping("/services") @PreAuthorize("hasAnyRole('OWNER','MANAGER')") ResponseEntity<TherapyServiceResponse> service(@jakarta.validation.Valid @RequestBody TherapyServiceRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(TherapyServiceResponse.of(services.save(new TherapyService(r.name(),r.suggestedDurationMinutes(),r.defaultPrice(),r.requiredEquipment()))));}
 @PostMapping("/blocks") @PreAuthorize("hasAnyRole('OWNER','MANAGER','RECEPTION','SPECIALIST')") ResponseEntity<BlockResponse> block(@jakarta.validation.Valid @RequestBody BlockRequest r){if((r.specialistId()==null)==(r.roomId()==null))throw new IllegalArgumentException("Blokada musi dotyczyć dokładnie jednego zasobu");if(!r.endsAt().isAfter(r.startsAt()))throw new IllegalArgumentException("Nieprawidłowy zakres blokady"); Specialist s=r.specialistId()==null?null:specialists.findById(r.specialistId()).orElseThrow(()->new NoSuchElementException("Nie znaleziono specjalisty"));Room room=r.roomId()==null?null:rooms.findById(r.roomId()).orElseThrow(()->new NoSuchElementException("Nie znaleziono gabinetu"));return ResponseEntity.status(HttpStatus.CREATED).body(BlockResponse.of(blocks.save(new AvailabilityBlock(s,room,r.startsAt(),r.endsAt(),r.type(),r.reason()))));}
}
